select
id
,last_login_time
,login_type
,created_at
,has_login
,type
,account_owner
,archived
,user_settings
,updated_at
,mobile_phone
,user_type_id
,first_name
,email
,thumbnail
,_fivetran_batch
,license_type
,approver_user_ids
,last_name
,billability_target
,hire_date
,display_name
,billable
,invitation_pending
,billrate
,deleted
,_fivetran_index
,approvee_user_ids
,guid
,location
,_fivetran_synced
,archived_at
,termination_date
,employee_number
,deleted_at
from   {{ source('resource_manager', 'resource_manager_users') }}