select
id
,starts_at
,owner_id
,description
,created_at
,type
,archived
,updated_at
,use_parent_bill_rates
,project_state_id
,client
,ends_at
,settings
,secureurl
,thumbnail
,owner_name
,_fivetran_batch
,timeentry_lockout
,has_pending_updates
,project_state
,project_code
,tags
,_fivetran_index
,parent_id
,name
,guid
,phase_name
,_fivetran_synced
from  {{ source('resource_manager', 'resource_manager_project_phases') }}